import pymysql
config={'host':'127.0.0.1','user':'root','password':'1234','database':'work','port':3306,'charset':'utf8','use_unicode':True}


try :
    conn = pymysql.connect(**config)
    cursor = conn.cursor()

    round = int(input('회차 입력:'))
    num1=int(input('첫번째 숫자 입력:'))
    num2=int(input('두번째 숫자 입력:'))
    num3=int(input('세번째 숫자 입력:'))
    num4=int(input('네번째 숫자 입력:'))
    num5=int(input('다섯번째 숫자 입력:'))
    num6=int(input('여섯번째 숫자 입력:'))
    bonus_num=int(input('보너스 숫자 입력:'))

    sql=f"insert into lotto_history(round,num1,num2,num3,num4,num5,num6,bonus_num) values({round},{num1},{num2},{num3},{num4},{num5},{num6},{bonus_num})"
    cursor.execute(sql)
    conn.commit()

except Exception as e:
    print('db 연동 오류:',e)
    conn.rollback()

finally:
    cursor.close()
    conn.close()

